spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    show-sql: false

  ai:
    vertex:
      ai:
        gemini:
          project-id: ${GCP_PROJECT_ID}
          location: ${GCP_LOCATION:us-central1}
          chat:
            options:
              model: gemini-2.0-flash
        embedding:
          project-id: ${GCP_PROJECT_ID}
          location: ${GCP_LOCATION:us-central1}
          text:
            options:
              model: text-embedding-005

app:
  security:
    api-key: ${API_KEY}
    allowed-origins:
      - ${FRONTEND_ORIGIN}
    allowed-ips: ${ALLOWED_IPS:}
  storage:
    gcs:
      bucket-name: ${GCS_BUCKET_NAME}
